### ISSUE TITLE
Laravel 5.5 support

### ISSUE THREAD

**Issue by SanderMuller** [Devitek/eloquent-loggable#2]
Could you add Laravel 5.5 support?

Debug info:

```
File:  /vendor/laravel/framework/src/Illuminate/Database/Connection.php on line: 664
-- | --
Exceptiontype:  Illuminate\Database\QueryException
Error message:  SQLSTATE[42000]: Syntax error or  access violation: 1064 You have an error in your SQL syntax; check the  manual that corresponds to your MySQL server version for the right  syntax to use near 'json null, `user_id` varchar(191) null) default  character set utf8mb4 collate ut' at line 1 (SQL: create table  `ext_log_entries` (`id` int unsigned not null auto_increment primary  key, `action` varchar(8) not null, `logged_at` datetime not null,  `loggable_id` int not null, `loggable_type` varchar(191) not null,  `version` int not null, `reason` varchar(191) null, `data` json null,  `user_id` varchar(191) null) default character set utf8mb4 collate  utf8mb4_unicode_ci)

Trace:  #0  /vendor/laravel/framework/src/Illuminate/Database/Connection.php(624):  Illuminate\Database\Connection->runQueryCallback('create table  `e...', Array, Object(Closure)) #1  /vendor/laravel/framework/src/Illuminate/Database/Connection.php(459):  Illuminate\Database\Connection->run('create table `e...', Array,  Object(Closure)) #2  /vendor/laravel/framework/src/Illuminate/Database/Schema/Blueprint.php(86):  Illuminate\Database\Connection->statement('create table `e...') #3  /vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(252):   Illuminate\Database\Schema\Blueprint->build(Object(Illuminate\Database\MySqlConnection),  Object(Illuminate\Database\Schema\Grammars\MySqlGrammar)) #4  /vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(165):   Illuminate\Database\Schema\Builder->build(Object(Illuminate\Database\Schema\Blueprint)) #5  /vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221):  Illuminate\Database\Schema\Builder->create('ext_log_entries',  Object(Closure)) #6  /database/migrations/2015_07_18_163847_create_log_entries.php(25):  Illuminate\Support\Facades\Facade::__callStatic('create', Array) #7 /vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(359): CreateLogEntries->up() #8  /vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(365):   Illuminate\Database\Migrations\Migrator->Illuminate\Database\Migrations\{closure}() #9  /vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(177):   Illuminate\Database\Migrations\Migrator->runMigration(Object(CreateLogEntries),  'up') #10  /vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(146):  Illuminate\Database\Migrations\Migrator->runUp('/var/www/html/m...',  50, false) #11  /vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(95):  Illuminate\Database\Migrations\Migrator->runPending(Array, Array) #12  /vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(69):  Illuminate\Database\Migrations\Migrator->run(Array, Array) #13 [internal function]: Illuminate\Database\Console\Migrations\MigrateCommand->handle() #14  /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29):  call_user_func_array(Array, Array) #15  /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87):  Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() #16  /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31):   Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application),  Array, Object(Closure)) #17  /vendor/laravel/framework/src/Illuminate/Container/Container.php(549):   Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application),  Array, Array, NULL) #18  /vendor/laravel/framework/src/Illuminate/Console/Command.php(180):  Illuminate\Container\Container->call(Array) #19 /vendor/symfony/console/Command/Command.php(262):   Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput),  Object(Illuminate\Console\OutputStyle)) #20  /vendor/laravel/framework/src/Illuminate/Console/Command.php(167):   Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput),  Object(Illuminate\Console\OutputStyle)) #21 /vendor/symfony/console/Application.php(888):  Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput),  Object(Symfony\Component\Console\Output\ConsoleOutput)) #22 /vendor/symfony/console/Application.php(224):  Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\Migrations\MigrateCommand),  Object(Symfony\Component\Console\Input\ArgvInput),  Object(Symfony\Component\Console\Output\ConsoleOutput)) #23 /vendor/symfony/console/Application.php(125):  Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput),  Object(Symfony\Component\Console\Output\ConsoleOutput)) #24  /vendor/laravel/framework/src/Illuminate/Console/Application.php(88):   Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput),  Object(Symfony\Component\Console\Output\ConsoleOutput)) #25  /vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121):   Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput),  Object(Symfony\Component\Console\Output\ConsoleOutput)) #26 /artisan(35):  Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput),  Object(Symfony\Component\Console\Output\ConsoleOutput)) #27 {main}
-- | --
```

Please let me know if I can provide any more information

**Comment by CaporalDead** [comment]
Hi @Rhinni , I will try to look at it today ! I'll keep you up to date.
